databases:
  - name: segmentationdb
    plan: free
    databaseName: segdb
    user: bsaid

services:
  - type: web
    plan: free
    name: segmentation
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn segmentation.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: segdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
